icssc/anteater-api

- apps/api/src/index.ts
Relocated the API reference page to /reference.
This should help prevent confusion between the docs hosted on docs.icssc.club and the reference hosted on anteaterapi.com
> feat: move api reference to /reference

- packages/db/drizzle.config.ts
- packages/db/package.json
- packages/db/src/index.ts
- packages/db/src/migrate.ts
While attempting to migrate the prod database to the latest version of the schema introduced in #12, I noticed that it failed due to a deadlock. Even after temporarily disabling the WebSoc scraper and killing all outstanding connections it would still resurface, and as it turns out limiting the connector to one connection resolved that issue.
Things are a bit murky because the old connections may not have been killed properly, but this should be a step in the right direction.
Aims to address #5, but the jury is still out on whether this resolves the issue.
Tested locally, migration succeeded.
> fix: resolve issues with deadlocking

- apps/api/package.json
- apps/data-pipeline/larc-scraper/package.json
- apps/data-pipeline/study-location-scraper/package.json
- apps/data-pipeline/websoc-scraper/package.json
- dump_db.sh
- package.json
- packages/db/migrations/0003_refactor.sql
- packages/db/migrations/meta/0003_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/package.json
- packages/db/src/schema.ts
- packages/public/libwebsoc-next/package.json
- pnpm-lock.yaml
[Drizzle 0.36.0](https://github.com/drizzle-team/drizzle-orm/releases/tag/0.36.0) introduced, among other features, a more concise array syntax for indexes and constraints.
This PR upgrades our dependencies, migrates our schema to that syntax, and also addresses some key issues, namely:
- Indexes for GE categories other than Category Ia were incorrectly indexed based on whether the course's `is_ge_1a` field is true, regardless of what the index was actually named. This PR corrects this issue.
- In a similar vein, this PR removes custom index names for all indexes except the course/instructor search GIN indexes, to minimize noise which caused a false sense of correctness.
- Updated the `dump_db` script to also dump the `drizzle` schema, which Drizzle uses to track migrations. This resolves …
> refactor: db enhancements

- apps/data-pipeline/course-scraper/src/index.ts
- apps/data-pipeline/study-location-scraper/src/handler.ts
- apps/data-pipeline/study-location-scraper/src/lib.ts
- apps/data-pipeline/websoc-scraper/src/lib.ts
- packages/db/migrations/0004_enhance_scraper.sql
- packages/db/migrations/meta/0004_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/migrate.ts
- packages/db/src/schema.ts
Changes to the study room scraper:
- Update database schema to ensure uniqueness of each (study room ID, start, end) tuple. This resolves the issue of that table ballooning to many millions of rows.
Changes to the WebSoc scraper:
- Remove the `DEFAULT NOW` directive for `updated_at` columns to ensure it will be updated by the scraper on an upsert.
- Add a column to the `websoc_meta` table that tracks the last department that was scraped successfully. If this column is not null for any term eligible to be scraped, the scraper will prioritize that term and start where the scraper left off.
Misc fixes:
- Explicitly close the connection upon scraper/migration termination to avoid possible deadlocks.
Closes #4.
For the study location scraper:
- Run scraper once locally.
- Run `SELECT COUNT(1) …
> feat: scraper enhancements

- apps/api/src/schema/search.ts
- apps/api/src/services/search.ts
Add the `resultType` flag that dictates what types of results are returned by the search endpoint. Can be `course` or `instructor`. Behavior is the same as the endpoint currently if not provided.
Tested locally with queries using the new flag.
> feat(search): implement resultType flag

- apps/api/src/graphql/schema/search.ts
- apps/api/src/rest/routes/search.ts
- apps/api/src/schema/search.ts
- apps/api/src/services/search.ts
Return the total matched result count in the search response.
Required for PeterPortal integration since they expect a total result count for pagination purposes.
Tested locally, verified that performance loss from pagination in JS is negligible (based on #23).
> feat!: return count in search response

- apps/api/src/graphql/resolvers/courses.ts
- apps/api/src/graphql/resolvers/instructors.ts
- apps/api/src/graphql/schema/courses.ts
- apps/api/src/graphql/schema/instructors.ts
- apps/api/src/rest/routes/courses.ts
- apps/api/src/rest/routes/instructors.ts
- apps/api/src/schema/courses.ts
- apps/api/src/schema/instructors.ts
- apps/api/src/services/courses.ts
- apps/api/src/services/instructors.ts
- apps/api/src/services/search.ts
Add support for fetching courses/instructors in a bulk, given a set of IDs.
We have been able to support batch queries for a long time but have never done so (mostly due to my poor planning). This should remove the need for consumers to query our API _N_ times for _N_ things, if they already know exactly what they want.
Tested locally.
> feat: batch endpoints for courses/instructors

- apps/api/src/rest/routes/courses.ts
- apps/api/src/schema/courses.ts
Revert `prerequisiteTreeSchema` to what it was originally. Also, override the OpenAPI metadata on it so it doesn't cause any errors, and set the metadata properly so consumers can receive the correct type data.
Honestly this was a lot less involved than I expected.
Closes #28.
Now we won't have to hardcode the prereq tree type in the API's consumers.
- Run dev server locally.
- Use [`openapi-typescript`](https://github.com/openapi-ts/openapi-typescript) to generate a types file from the dev server.
- Paste the following snippet into another TS file and play around with it, ensuring that the `PrerequisiteTree` type behaves as expected.
```ts
// assuming the output is named "anteater-api-types.ts"
import { components } from "./anteater-api-types";
type PrerequisiteTree = …
```
> feat: properly type prerequisite tree

- CONTRIBUTORS.md
- apps/api/src/graphql/resolvers/websoc.ts
Fix the bug in #52 by actually returning the fetched result from Postgres.
A single `return` is added.
Fixes #52.
See above.
Tested on a local deployment.
Postman was used to verify fix was effective.
Aforementioned query now works locally:
> fix(websoc): graphql terms actually transmitted

- apps/api/src/schema/week.ts
Corrects schema to allow passing of year, month, and date from GraphQL for week information.
Instead of accepting a string and manually calling `parseInt` to parse it, we use Zod's `z.coerce.number()`.
`z.number()` is unacceptable since this would break REST, where the arguments arrive as strings.
Fixes #54.
Fixes an active production bug.
Tested on a local deployment. Parity was ensured between REST and GraphQL.
GraphQL is working (the goal of this PR):
REST is working as previously:
> fix(week): correct parsing of graphql day

- apps/api/src/graphql/schema/search.ts
- apps/api/src/schema/search.ts
Retype the type of the count property on the search for instructor/course endpoint as an integer.
Resolves #56.
As explained in the issue, this is the correct type for this value from a mathematical standpoint.
This is technically a breaking change but:
* It only affects users where integers and floats are not the same (i.e. not JS/TS).
* It only affects people who somehow depended on incorrect behavior.
Local testing was done to ensure neither GraphQL nor REST are broken by this change.
Note that token checks were disabled in this local deployment to simplify local testing.
Observe that Postman introspects the new type correctly and the endpoint works as expected:
REST continues to work:
> fix(search): count is a nonnegative int

- apps/api/src/schema/grades.ts
As specified in the issue, `excludePNP` is broken for GraphQL grades endpoints. Zod expects a string, which is impossible when schema expects boolean. Fixed by coercing to string before parsing.
`z.coerce.boolean()` is unacceptable since `Boolean("false") === true` which is not what we want.
Fixes #62.
i just wanna use API man
Tested with Postman on a local deployment.
Schema validation still works, of course:
> fix: excludePNP parsing for GraphQL

- .github/actions/setup-node-and-pnpm/action.yml
- .github/workflows/delete_staging.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- apps/api/wrangler.toml
Initial version of the CI pipeline, long overdue.
Closes #26.
~~GitHub reads actions workflows from `main` so cannot be tested yet. Should merge this first then iron out any issues that manifest on other PRs when enabled.~~
Just kidding, it works somehow? Let's see if things break.
> ci: init pipeline

- apps/api/src/services/grades.ts
> fix: excludePNP nesting in grades query builder

- apps/api/src/services/grades.ts
As described in analysis on the linked issue, add a missing join to prevent `aggregateGradesByCourse` from failing when passing an instructor to filter by.
Fixes #70.
Fixes endpoint failure as described in linked issue.
REST and GraphQL were both examined on a local deployment, following the reproduction steps from the linked issue. The issue is no longer present.
REST is working:
GraphQL is working:
> fix(grades): missing join broke aggregateGradesByCourse

- apps/api/src/schema/websoc.ts
Updated the error message for the required quarter parameter in the WebSoc query schema. Previously, when the quarter parameter was omitted, the error message stated: "Required". The new message is more specific, telling the user that the quarter parameter is required.
Link to issue #72
When programmers were making websoc queries without the quarter parameter, the previous message was not helpful and unclear on what was missing. This change makes the API more clear in showing what is required when the quarter parameter is absent from the query.
By running and hosting the API locally with Docker and pnpm, I was able to test my changes and confirm the results I was striving for while also confirming that there were no errors and that nothing broke in the process. The tests I ran included …
> feat(websoc): enhance WebSoc quarter parameter validation message

- apps/key-manager/.env.example
- apps/key-manager/docker-compose.yml
- apps/key-manager/package.json
- apps/key-manager/src/components/auth/SignOut.tsx
- apps/key-manager/src/components/key/KeyManager.tsx
- apps/key-manager/src/components/key/view/KeyTableRow.tsx
- apps/key-manager/src/components/layout/Header.tsx
- apps/key-manager/src/components/ui/avatar.tsx
- pnpm-lock.yaml
> fix(key-manager): key manager setup & ui

- apps/api/src/schema/websoc.ts
- apps/data-pipeline/websoc-scraper/package.json
- apps/data-pipeline/websoc-scraper/src/lib.ts
- packages/db/migrations/0007_websoc_web.sql
- packages/db/migrations/meta/0007_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/schema.ts
- packages/public/libwebsoc-next/package.json
- packages/public/libwebsoc-next/src/index.ts
- pnpm-lock.yaml
Modified `libwebsoc-next` to support fetching the Web column, which links to the section's syllabus page, and is realized as the `webURL` field in the `WebsocSection` object.
Because this column is not reflected in the XML response, which `libwebsoc-next` parses into JSON, the module also fetches the web version concurrently with the XML version.
As a result, the timeouts after WebSoc query invocations in the scraper have been doubled.
Closes #41.
Unblocks icssc/AntAlmanac#1113.
Tested locally due to schema changes. Database dump available [here](https://anteater-api-dump.s3.us-west-1.amazonaws.com/db-pr-82.sql.gz).
> feat: add web column to WebSoc

- apps/api/src/schema/study-rooms.ts
- apps/data-pipeline/study-location-scraper/src/lib.ts
Followup to #75, fixing study room slot times being rendered in Postgres's local timezone.
We simply set the timezone on the connection acquired by the scraper to `America/Los_Angeles`.
Resolves #84. We both specify the intended behavior from #75 in the example and actually fulfill it.
Tested by setting Postgres's timezone to `America/New_York`, running the scraper, then testing the API request.
Despite forcing Postgres's global timezone to change, the timezone is correct since we set it on the session which takes precedence over the global setting:
We know this is effective because setting a different timezone for the scraper's SQL session uses that timezone instead:
So if we force `America/Los_Angeles` on the scraper session, it will give the correct offset regardless of Postgres or …
> fix(study-rooms): specify and serve UCI timezone for slots

- apps/api/src/graphql/resolvers/programs.ts
- apps/api/src/graphql/schema/programs.ts
- apps/api/src/rest/routes/programs.ts
- apps/api/src/schema/programs.ts
- apps/api/src/services/programs.ts
Previously, the endpoints for programs returned a comprehensive list of all `majors`, `minors`, and `specializations` without any filtering options. With this update, we have added the ability to query specific data by including optional parameters like `majorId` or `minorId`. This enhancement allows users to request only the relevant `specializations` associated with a particular `major` or `minor`, streamlining the data retrieval process and improving the overall user experience.
`/v2/rest/programs/specializations` should have some way to filter by major id - #96 
Currently, the endpoint returns a list of all available specializations, which can be overwhelming and inefficient, especially for users seeking information about a specific `major`. By implementing this fix, users will be …
> feat: add way to filter `programs` endpoints by `majorid` and `id`

- apps/api/src/services/programs.ts
Silly bugfix.
Fix #98.
just don't have a bug
Tested locally with Postman.
Majors with no specializations are now present:
The number of majors in the `major` table is 270. All of them appear in the response:
```
Welcome to Node.js v23.5.0.
Type ".help" for more information.
> const {data} = await fetch("http://localhost:8787/v2/rest/programs/majors").then(r => r.json())
undefined
> data.length
270
> 
```
> fix(programs): add majors with no specializations

- apps/api/src/graphql/resolvers/courses.ts
- apps/api/src/graphql/resolvers/instructors.ts
- apps/api/src/graphql/schema/courses.ts
- apps/api/src/graphql/schema/instructors.ts
- apps/api/src/rest/routes/courses.ts
- apps/api/src/rest/routes/instructors.ts
- apps/api/src/services/courses.ts
- apps/api/src/services/instructors.ts
Fix the issue described below, introduced in #101.
Fix #107.
we can just debug things
Tested on local deployment
> hotfix(courses,instructors): correct batch route precedence

- apps/api/src/graphql/resolvers/programs.ts
- apps/api/src/graphql/schema/programs.ts
- apps/api/src/rest/routes/programs.ts
- apps/api/src/schema/programs.ts
- apps/api/src/services/programs.ts
- apps/data-pipeline/degreeworks-scraper/src/components/AuditParser.ts
- apps/data-pipeline/degreeworks-scraper/src/components/DegreeworksClient.ts
- apps/data-pipeline/degreeworks-scraper/src/components/Scraper.ts
- apps/data-pipeline/degreeworks-scraper/src/index.ts
- apps/data-pipeline/degreeworks-scraper/src/types.ts
- packages/db/migrations/0009_uc_ge_requirements.sql
- packages/db/migrations/meta/0009_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/schema.ts
We scrape and serve undergraduate requirements, i.e. UC and GE requirements, which are required to earn any undergraduate degree but are not considered part of any major.
* The DegreeWorks scraper now acquires this data and saves it to the new `school_requirement` table.
* A new requirement type, the marker requirement, is introduced. This represents any requirement which is to be marked manually by an advisor and is not completed by coursework. **This PR conjectures that such requirements, when not complete, are labelled as "Incomplete".** Based on my own view of DegreeWorks I only observe "Complete", so this other variant is a guess.
* We now systematically replace the word "satisfied" with "required", when preceded by a space, from the name of any requirement. This is because the names …
> feat(programs): undergrad program requirements

- apps/api/src/services/websoc.ts
- apps/data-pipeline/websoc-scraper/src/lib.ts
- packages/stdlib/src/int-utils.ts
`conflictUpdateSetAllCols` cannot disambiguate updating a column to `NULL` and deferring to the existing value, causing the issue mentioned below. We fix this by storing a sentinel `-1` and checking for this in the service layer, a minor overhead.
This affects the following columns of `websoc_section` and no other uses of `conflictUpdateSetAllCols` (since those columns are not nullable):
```sql
status, num_on_waitlist, num_waitlist_cap, num_new_only_reserved, num_currently_total_enrolled, num_currently_section_enrolled
```
Fix #112
anteater api no prod bug challenge
ran REST manually
Sanity check: all sections returned by `fullOnly` for Winter 2025 now correctly report an empty waitlist and waitlist cap.
Second sanity check: no `websoc_section` rows for Winter 2025 have any waitlist …
> fix(websoc): store sentinels for null due to quirk

- apps/data-pipeline/websoc-scraper/src/lib.ts
Execute recommendation in #110.
Currently, when `libwebsoc-next` finds more than 900 sections, it immediately throws.
In the context of our current scraping strategy using chunks of the section space, a chunk thought to contain less than 900 sections may be found (and, in practice, has been found) to actually contain more than 900 sections, causing the scraping of that chunk to fail, crashing the scraper.
A later run would crash too, at the exact same point.
So a violation of our current assumptions is fatal.
Change `SECTIONS_PER_CHUNK` to something greater than 900 (the higher, the more often the failsafe will trigger).
This will simulate more than 900 sections being found in a chunk.
Observe in this printout as a chunk is found to be too large and bisected once, which is successful:
``` …
```
> feat(websoc): bisect to handle section chunk overrun

- apps/data-pipeline/degreeworks-scraper/src/components/AuditParser.ts
- packages/db/migrations/0010_shortened_dept.sql
- packages/db/migrations/meta/0010_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/schema.ts
This PR aims to address two key issues with our handling of wildcards.
For reasons that were never documented, wildcards for an entire department with no other qualifier (e.g. BIOSCI @) were never properly handled. This PR implements handling for such cases by dumping all courses in the department. This is a substantial amount of data, but no feasible workaround exists as department-wide wildcards may cohabitate with other complex requirements.
While implementing this feature, I noted that the department code given by DegreeWorks is the shortened version (without whitespace). A generated column and index thereon is added so that this data is readily and correctly accessible by the scraper.
We also aim to correct our previous incorrect assumption of what the wildcard `@` translates to. …
> feat(dw-scraper): better wildcard handling

- apps/api/src/rest/routes/programs.ts
Fix typo failing type checks and rendering #119 ineffective with respect to specializations. Also correct the error message to correctly describe the situation.
Fix #127.
It typechecks correctly now.
> fix(programs): incorrect property access

- apps/data-pipeline/ap-exams-importer/src/data.ts
Fix a typo in the course credit granted for AP Calculus BC.
Introduced in #129.
#144
> fix: typo on AP calc BC

- apps/data-pipeline/course-scraper/src/index.ts
At the start of the 2024-25 academic year, I&C SCI 32A was renamed to I&C SCI H32.
Because the school is incapable of being internally consistent, some courses have had their prerequisites updated to only require H32 where it previously required 32A, while others continue to require 32A. Perplexingly, some courses require both, which has greatly complicated the solution.
This shim introduced into the courses scraper should, for all courses that have 32A or H32 as a prerequisite, introduce an equivalent H32 node into the prerequisite tree where a 32A node exists, and _vice versa_. Courses that already have both courses as a prerequisite are left unmodified.
cc: @Awesome-E (stakeholder)
Closes icssc/peterportal-client#609.
Closes icssc/peterportal-client#627.
Allows students with 32A or H32 …
> feat: implement shim for 32A/H32 equivalence

- apps/api/src/services/search.ts
- packages/db/migrations/0002_search_indexes.sql
- packages/db/migrations/0013_search_index_dept.sql
- packages/db/migrations/meta/0013_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/schema.ts
- Added `SETWEIGHT(TO_TSVECTOR('english', COALESCE(course.shortenedDept, '')), 'B')` to the `COURSES_WEIGHTS` definition in `apps/api/src/services/search.ts`
- This ensures searches including department codes with numbers (e.g. “UNI STU1”) are matched by Postgres’s full-text vector
#100 
Before this change, searches combining a department code and course number could match inconsistently. “UNI STU1” (with a space) would return results, but “UNISTU1” (no space) would not, or vice-versa. By including shortenedDept in our weighted TS-vector, both forms now resolve to the same underlying course code, fixing that inconsistency.
Tested locally by creating migrations and with localhost.
****ARTHIS and ART HIS has different search count -> need a new solution as well as for departments with no …
> feat(search): include shortenedDept in TS vector weighting

- packages/db/migrations/0014_study-rooms-left-join.sql
- packages/db/migrations/meta/0014_snapshot.json
- packages/db/migrations/meta/_journal.json
- packages/db/src/schema.ts
Fix issue below which failed to handle `NULL` slots when a left join found no slots to join to.
Zod was not expecting this and throws.
The fix is to simply throw these nulls out.
Fix #165.
it works now
You can simulate the error condition by deleting all study room slots for a room.
> fix(study-rooms): rooms with no slots

- apps/data-pipeline/degreeworks-scraper/src/components/DegreeworksClient.ts
Fix #180.
Correct URL determined by Network tab of inspect element.
Scraper is known to be working now.
No need to re-run scraper or update any data at this time.
No schema or docs change.
> fix(degreeworks-scraper): fix getMapping url

- apps/data-pipeline/course-scraper/src/index.ts
rewrote `scrapeCoursesInDepartment` to parse per-course `.courseblock` elements and their `.detail-*` children instead of relying on newline-splitting. This matches the current catalogue HTML and removes brittleness around formatting changes.
also addressed missing `departmentAlias` in course by adding a mapping on completed scrape
addresses #192, #193, #195, #152
course scraper needs to be fixed to run for the 25/26 academic year
current testing status shows that entries for courses are accurately updated with the exception of `shortened_dept` and `department_alias`. shortened dept is addressed when running migration 10, but the setting of `department_alias` needs further investiagion
> fix: course scraper adjustment for "courseblock"  change

- apps/data-pipeline/course-scraper/src/index.ts
fix class selector not scraping "same as" properly from catalogue
> fix(course-scraper): correct "same as"

- apps/api/src/services/search.ts
By asking the database to return the type of a search result, we can discern which table the result came from (courses or instructors).
We then use this to look the ID up in the correct table.
Since we are now using two distinct maps keyed by ID (one for course IDs, one for instructor IDs), it is now possible to return two entities of different types with identical ID.
This also has the side effect of reducing failed ID lookups since we never look up an instructor ID as a course or vice versa.
By the third statement above, we fix issue #188.
> fix: unified search results of different types can't clobber each other

- apps/data-pipeline/degreeworks-scraper/package.json
- apps/data-pipeline/degreeworks-scraper/src/components/DegreeworksClient.ts
- apps/data-pipeline/degreeworks-scraper/src/components/Scraper.ts
- apps/data-pipeline/degreeworks-scraper/src/components/schema.ts
- apps/data-pipeline/degreeworks-scraper/src/index.ts
- apps/data-pipeline/degreeworks-scraper/src/types.ts
- pnpm-lock.yaml
This closes #156.
We use the data backing the table at https://www.reg.uci.edu/mdsd/ to gather the list of valid "majors" at UCI. This term is used informally because it is a somewhat overloaded term. There are actually several parts to a major:
- The "school", with a unique code, e.g. Social Sciences.
- The "major", with a unique code, e.g. Cognitive Sciences.
- The "degree", with a unique code, e.g. B.S.
The combination of these three (and the correct department, but we don't need that for reasons explained in the code) forms the colloquial notion of a "major". Note that this also applies to graduate programs.
The identifiers describing schools and majors in this table align exactly with DegreeWorks. However, the degree code has no parallel in DegreeWorks. We instead attempt to matching …
> feat(degreeworks-scraper): discover and scrape only majors that exist 

- apps/data-pipeline/degreeworks-scraper/src/components/DegreeworksClient.ts
This closes #212.
This is a simple fix exactly as specified by the issue; we properly attempt the scrape in the later academic year before evaluating whether we need to fall back to the earlier academic year.
The scraper in this PR correctly determines that the 2025-2026 catalogue is available on DegreeWorks as of right now, so this change works.
> fix(degreeworks-scraper): correct catalogue year inference

- apps/data-pipeline/degreeworks-scraper/.gitignore
- apps/data-pipeline/degreeworks-scraper/src/components/AuditParser.ts
- apps/data-pipeline/degreeworks-scraper/src/components/DegreeworksClient.ts
- apps/data-pipeline/degreeworks-scraper/src/components/Scraper.ts
- apps/data-pipeline/degreeworks-scraper/src/index.ts
- apps/data-pipeline/degreeworks-scraper/src/types.ts
Closes #209.
See the description there for our motivation.
Instead of looking at the list of specializations in a major (which is no longer consistently provided), we look at the list of overall specializations and try to match each one to a major.
Some specializations do not match with any major at all. The only way to resolve this is to attempt every combination of specialization and major; valid combinations return the specialization block.
Upon analysis, there does seem to be some method to the madness.
The previous soft convention associating specialization code with their respective major code still appears intact.
This is also progress toward #210 because the list of specializations previously provided was given as advice when a specialization was not selected for a major which …
> fix(degreeworks-scraper): infer specialization-major association

- apps/data-pipeline/degreeworks-scraper/src/index.ts
Fixes issue introduced in #183.
This is a simple typo.
This only affects the first stage of ETL, so existing SQL rows, including those in production, continue to be accessible as if this issue did not exist.
> fix(degreeworks-scraper): incorrect construction of new database entity

- apps/api/src/schema/lib/year.ts
Solved issue #94 by explicitly comparing val to the empty string, null and undefined
Ran null, undefined, and empty string through localhost. Results in screenshots
> fix: explicit check for missing value in year schema
